cert_manager: prometheus-crd
    @echo cert_manager
chaoskube:
    @echo chaoskube
cilium: prometheus-crd
    @echo cilium
cloudflaredns:
    @echo cloudflaredns
cnpg: prometheus-crd stage1
    @echo cnpg
coredns: prometheus-crd
    @echo coredns
cypht:
#
dragonflydb: prometheus-crd
    @echo dragonflydb
external_dns: prometheus-crd
    @echo external_dns
external_secrets: prometheus-crd
    @echo external_secrets
grafana-config: keycloak-config grafana-deploy
#
grafana-deploy: grafana-operator
#
grafana-operator: prometheus-crd
    @echo grafana-operator
hcloud-ccm: prometheus-crd
    @echo hcloud-ccm
hcloud-csi: prometheus-crd
    @echo hcloud-csi
hostfirewall: cilium
    @echo hostfirewall
hosts:
#
keycloak-config: keycloak-deploy
    @echo keycloak-config
keycloak-deploy: prometheus-crd
    @echo keycloak-deploy
kubernetes-dashboard: prometheus-crd
    @echo kubernetes-dashboard
local_path_provisioner: prometheus-crd
    @echo local_path_provisioner
mariadb_deploy: mariadb_operator
    @echo mariadb_deploy
mariadb_operator: prometheus-crd
    @echo mariadb_operator
migadumail:
    @echo migadumail
nextcloud: cnpg pg-cluster-config
#
nginx: prometheus-crd
    @echo nginx
nix:
#
oauth_proxy:
#
pg-cluster-config: cnpg
    @echo pg-cluster-config
pgadmin4: pg-cluster-config
    @echo pgadmin4
postgrest: pg-cluster-config keycloak-config
    @echo postgrest
prometheus: prometheus-crd
    @echo prometheus
prometheus-crd: stage1 hosts
    @echo prometheus-crd
registry: prometheus-crd
    @echo registry
reloader: prometheus-crd
    @echo reloader
roundcube: pg-cluster-config prometheus-crd
#
stage1:
    @echo stage1
supabase:
#
test:
#
vault: prometheus-crd
#
vault-root-config: vault
#
victoriametrics-operator: prometheus-crd
    @echo victoriametrics-operator
victoriametrics-k8s-stack: victoriametrics-operator grafana-operator
    @echo victoriametrics-k8s-stack
