apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  annotations:
    knix-expr: hello
  name: ubuntu
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu:22.04
    name: ubuntu-pod
