apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: admin
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: admin
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: client-secret
                      name: client-secret
  config:
    server:
      root_url: https://grafana.lillecarl.com
    log:
      mode: console
    analytics:
      check_for_updates: "false"
    auth.generic_oauth:
      enabled: "true"
      name: "Keycloak"
      allow_sign_up: "true"
      auto_login: "true"
      client_id: "grafana"
      client_secret: local.rs.keycloak-config.grafana_client_secret
      scopes: "openid email profile roles"
      auth_url: "https://keycloak.lillecarl.com/realms/master/protocol/openid-connect/auth"
      token_url: "https://keycloak.lillecarl.com/realms/master/protocol/openid-connect/token"
      api_url: "https://keycloak.lillecarl.com/realms/master/protocol/openid-connect/userinfo"
      email_attribute_path: "email"
      groups_attribute_path: "groups"
      login_attribute_path: "username"
      name_attribute_path: "full_name"
      role_attribute_path: "contains(realm_access.roles[*], 'grafana-admin') && 'GrafanaAdmin' || contains(realm_access.roles[*], 'admin') && 'Admin' || contains(realm_access.roles[*], 'editor') && 'Editor' || 'Viewer'"
      allow_assign_grafana_admin: "true"
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
    spec:
      ingressClassName: nginx
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.lillecarl.com
      rules:
        - host: grafana.lillecarl.com
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
