# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "ehci_pci"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "e1000e"
    "r8169"
    "bcma"
  ];
  #boot.initrd.kernelModules = [ "e1000e" "r8169" "bcma" ];
  boot.extraModprobeConfig = "options vfio-pci ids=1002:67b1,1002:aac8";
  boot.blacklistedKernelModules = [ "amdgpu" "radeon" ];
  boot.kernelPackages = with pkgs.linuxKernel.packages; linux_xanmod;
  boot.kernelModules = [ "kvm-intel" "wl" "vfio_virqfd" "vfio_pci" "vfio_iommu_type1" "vfio" "i2c-dev" ];
  boot.kernelParams = [ "amd_iommu=on" "intel_iommu=on" "mitigations=off" "kvm.nx_huge_pages=off" ];

  boot.extraModulePackages = with config.boot.kernelPackages; [
    usbip
  ];

  boot.kernel.sysctl = {
    "vm.swappiness" = 1;
  };

  fileSystems."/" =
    { device = "zroot/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zroot/root/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/root/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7774-7A15";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/706e9add-3b1c-49b4-94b0-795218b393ac"; }
    ];

  hardware.enableAllFirmware = true;
  powerManagement.cpuFreqGovernor = "performance";
}
