apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
  namespace: pg-cluster
spec:
  backup:
    barmanObjectStore:
      destinationPath: s3://postspace-pg-cluster  # The S3 bucket path where backups will be stored
      endpointURL: https://5456ceefee94cfc7fa487e309956d7a2.eu.r2.cloudflarestorage.com  # Optional: S3-compatible endpoint URL (omit for AWS S3)
      s3Credentials:
        accessKeyId:
          name: r2-credentials  # Name of the Kubernetes secret
          key: ACCESS_KEY_ID    # Key in the secret containing the access key
        secretAccessKey:
          name: r2-credentials  # Name of the Kubernetes secret
          key: ACCESS_SECRET_KEY  # Key in the secret containing the secret key
      wal:
        compression: gzip  # Optional: Enable WAL compression (gzip)
        maxParallel: 8    # Optional: Number of parallel WAL operations
        # encryption: AES256  # Optional: Enable encryption
      data:
        compression: gzip  # Optional: Enable backup data compression
        # encryption: AES256  # Optional: Enable encryption
  managed:
    roles:
      - name: keycloak
        ensure: present
        passwordSecret:
          name: cluster-keycloak
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
  instances: 1
  storage:
    size: 1Gi
