apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
  namespace: pg-cluster
spec:
  postgresql:
    parameters:
      wal_keep_size: "64MB"
  backup:
    barmanObjectStore:
      destinationPath: s3://postspace-pg-cluster
      endpointURL: https://5456ceefee94cfc7fa487e309956d7a2.eu.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: r2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: r2-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 1
        # encryption: AES256
      data:
        compression: gzip
        # encryption: AES256
    retentionPolicy: "30d"
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cluster"
              annotations:
                external-dns.alpha.kubernetes.io/target-type: "A"
                external-dns.alpha.kubernetes.io/hostname: postgres.lillecarl.com
            spec:
              type: LoadBalancer
    roles:
      - name: postgres-admin
        ensure: present
        passwordSecret:
          name: cluster-postgres-admin
        login: true
        superuser: true
        inRoles:
          - pg_monitor
          - pg_signal_backend
  instances: 2 # For failing over quickly when chaoskube bonks the master
  storage:
    size: 1Gi
