apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ferretdb-tls
  namespace: pg-cluster
spec:
  secretName: ferretdb-tls
  dnsNames:
    - mongo.lillecarl.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
