apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-backup-role
  namespace: pg-cluster
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["r2-credentials"]
