apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-backup-rolebinding
  namespace: pg-cluster
subjects:
  - kind: ServiceAccount
    name: cluster
roleRef:
  kind: Role
  name: cluster-backup-role
  apiGroup: rbac.authorization.k8s.io
