apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cluster-transaction-pooler
  namespace: pg-cluster
spec:
  cluster:
    name: cluster
  instances: 1
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters: {}
