apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: pgadmin
data:
  config_system.py: |
    CA_FILE = '/etc/ssl/certs/ca-bundle.crt',
    AUTHENTICATION_SOURCES = ['oauth2']
    OAUTH2_CONFIG = [
        {
            'OAUTH2_NAME': 'keycloak',
            'OAUTH2_DISPLAY_NAME': 'Keycloak',
            'OAUTH2_CLIENT_ID': 'pgadmin',
            'OAUTH2_CLIENT_SECRET': '$OAUTH2_CLIENT_SECRET',
            'OAUTH2_TOKEN_URL': 'https://keycloak.lillecarl.com/realms/master/protocol/openid-connect/token',
            'OAUTH2_AUTHORIZATION_URL': 'https://keycloak.lillecarl.com/realms/master/protocol/openid-connect/auth',
            'OAUTH2_API_BASE_URL': 'https://keycloak.lillecarl.com/realms/master/protocol/openid-connect',
            'OAUTH2_USERINFO_ENDPOINT': 'https://keycloak.lillecarl.com/realms/master/protocol/openid-connect/userinfo',
            'OAUTH2_SERVER_METADATA_URL': 'https://keycloak.lillecarl.com/realms/master/.well-known/openid-configuration',
            'OAUTH2_SCOPE': 'openid email profile',
            'OAUTH2_ICON': 'fa-key',
            'OAUTH2_BUTTON_COLOR': '#000000',
            
            # Claims mapping
            'OAUTH2_USERNAME_CLAIM': 'preferred_username',
            'OAUTH2_EMAIL_CLAIM': 'email',
            
            # Optional: Auto-create users that don't exist
            'OAUTH2_AUTO_CREATE_USER': True,
            
            # Optional: Additional parameters
            'OAUTH2_ADDITIONAL_PARAMS': {
                'access_type': 'offline'
            },
            'OAUTH2_SSL_CERT_VERIFICATION': False,
        }
    ]
