apiVersion: v1
kind: Service
metadata:
  name: testingress
  namespace: nginx
spec:
  ipFamilies:
  # - IPv4
  - IPv6
  ipFamilyPolicy: SingleStack
  loadBalancerClass: io.cilium/node
  loadBalancerIP: 2a01:4f9:c012:6632::2
  ports:
  - port: 443
    name: https
  selector:
    app.kubernetes.io/name: test-service
  sessionAffinity: None
  type: LoadBalancer
