#! /usr/bin/env python

import os
import socket
from pathlib import Path
from plumbum import local, FG

mktemp = local.cmd.mktemp
nix = local.cmd.nix
nixenv = local["nix-env"]
sudo = local.cmd.sudo

# A temp dir to build towards
tmpDir = mktemp(["-t", "-d", "nonixos-rebuild.XXXX"]).rstrip()
# get hostname
hostname = "nonixos"
#hostname = socket.gethostname()
# set profile name
profile = "nonixos"
# flake args, these aren't really experimental and flakes are the best
flakeargs = ["--extra-experimental-features", "nix-command flakes repl-flake"]
# where to store our build output temporarily
resultpath = f"{tmpDir}/result"
# profilepath
profilepath = f"/nix/var/nix/profiles/{profile}"
# nix flake path
flakepath = os.getcwd()

os.chdir(tmpDir)
nix[flakeargs + ["build", f"{flakepath}#nixosConfigurations.{hostname}.config.system.build.toplevel", "--profile", profile, "--out-link", resultpath, "--impure"]] & FG
sudo [nixenv["-p", profilepath, "--set", resultpath]] & FG

#rm -r @(tmpDir)
