apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: oauth2-proxy
spec:
  secretName: tls
  dnsNames:
    - oauthproxy.lillecarl.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
