apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: "${namespace}"
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
        environment: development
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      debug:
          addr: :5001
          prometheus:
            enabled: true
            path: /metrics
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
