# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "adler-32-1.2.0" = {
      name = "adler-32";
      packageName = "adler-32";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/adler-32/-/adler-32-1.2.0.tgz";
        sha512 = "/vUqU/UY4MVeFsg+SsK6c+/05RZXIHZMGJA+PX5JyWI0ZRcBpupnRuPLU/NXXoFwMYCPCoxIfElM2eS+DUXCqQ==";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha512 = "Ajr4IcMXq/2QmMkEmSvxqfLN5zGmJ92gHXAeOXq1OekoH2rfDNsgdDoL2f7QaRCy7G/E6TpxBVdRuNraMztGHw==";
      };
    };
    "any-json-3.1.0" = {
      name = "any-json";
      packageName = "any-json";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-json/-/any-json-3.1.0.tgz";
        sha512 = "p4sFflxj6pQzn7T1omWd63GI7bNRmoDgpqxQWJIWNEOWp2+Z8PYtUY/DTGu7QA3MnSBpf7E+cDT3ZNQmeg+WNg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "arguments-extended-0.0.3" = {
      name = "arguments-extended";
      packageName = "arguments-extended";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/arguments-extended/-/arguments-extended-0.0.3.tgz";
        sha512 = "MNYdPKgCiywbgHAmNsYr1tSNLtfbSdwE1akZV+33hU9A8RG0lO5HAK9oMnw7y7bjYUhc04dJpcIBMUaPPYYtXg==";
      };
    };
    "array-buffer-byte-length-1.0.1" = {
      name = "array-buffer-byte-length";
      packageName = "array-buffer-byte-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-buffer-byte-length/-/array-buffer-byte-length-1.0.1.tgz";
        sha512 = "ahC5W1xgou+KTXix4sAO8Ki12Q+jf4i0+tmk3sC+zgcynshkHxzpXdImBehiUYKKKDwvfFiJl1tZt6ewscS1Mg==";
      };
    };
    "array-extended-0.0.11" = {
      name = "array-extended";
      packageName = "array-extended";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-extended/-/array-extended-0.0.11.tgz";
        sha512 = "Fe4Ti2YgM1onQgrcCD8dUhFuZgHQxzqylSl1C5IDJVVVqY5D07h8RghIXL9sZ6COZ0e+oTL5IusTv5eXABJ9Kw==";
      };
    };
    "array.prototype.reduce-1.0.7" = {
      name = "array.prototype.reduce";
      packageName = "array.prototype.reduce";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/array.prototype.reduce/-/array.prototype.reduce-1.0.7.tgz";
        sha512 = "mzmiUCVwtiD4lgxYP8g7IYy8El8p2CSMePvIbTS7gchKir/L1fgJrk0yDKmAX6mnRQFKNADYIk8nNlTris5H1Q==";
      };
    };
    "arraybuffer.prototype.slice-1.0.3" = {
      name = "arraybuffer.prototype.slice";
      packageName = "arraybuffer.prototype.slice";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/arraybuffer.prototype.slice/-/arraybuffer.prototype.slice-1.0.3.tgz";
        sha512 = "bMxMKAjg13EBSVscxTaYA4mRc5t1UAXa2kXiGTNfZ079HIWXEkKmkgFrh/nJqamaLSrXO5H4WFFkPEaLJWbs3A==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha512 = "NfJ4UzBCcQGLDlQq7nHxH+tv3kyZ0hHQqF5BO6J7tNJeP5do1llPr8dZ8zHonfhAu0PHAdMkSo+8o0wxg9lZWw==";
      };
    };
    "available-typed-arrays-1.0.7" = {
      name = "available-typed-arrays";
      packageName = "available-typed-arrays";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/available-typed-arrays/-/available-typed-arrays-1.0.7.tgz";
        sha512 = "wvUjBtSGN7+7SjNpq/9M2Tg350UZD3q62IFZLbRAR1bSMlCo1ZaeW+BJ+D090e4hIIZLBcTDWe4Mh4jvUDajzQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "call-bind-1.0.7" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.7.tgz";
        sha512 = "GHTSNSYICQ7scH7sZ+M2rFopRoLh8t2bLSW6BbgrtLsahOIB5iyAVJf9GjWK3cYTDaMj4XdBpM1cA6pIS0Kv2w==";
      };
    };
    "cfb-0.11.1" = {
      name = "cfb";
      packageName = "cfb";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cfb/-/cfb-0.11.1.tgz";
        sha512 = "1GEqpcO365hTRpP+GzHXNiUF5SB7qmY5aVYwrJm8ISx27HzHpaFlTQhnOCMNhqP0WPkHR0OGE9WDSqtksV4anw==";
      };
    };
    "cfb-1.0.8" = {
      name = "cfb";
      packageName = "cfb";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/cfb/-/cfb-1.0.8.tgz";
        sha512 = "oA7VomcgZRWTo8V20UYLlXu4ZOCFEAfwwrcxE8PcVzXW12WOhsi38PVnymb6Xoj8y7ghoZQOOOVRBMdLJ4jCjg==";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha512 = "QVb0dM5HvG+uaxitm8wONl7jltx8dqhfU33DcqtOZcLSVIKSDDLDi7+0LbAKiyI8hD9u42m2YxXSkMGWThaecQ==";
      };
    };
    "codepage-1.12.2" = {
      name = "codepage";
      packageName = "codepage";
      version = "1.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/codepage/-/codepage-1.12.2.tgz";
        sha512 = "FAN+oPs/ocaPLFvIt4vEOHgWA6UJ6t+fVbbVBoXDpTpC+4JYasomYZEEjR/Miph3qQrVnIShRwwmwu4P35JW1w==";
      };
    };
    "codepage-1.15.0" = {
      name = "codepage";
      packageName = "codepage";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/codepage/-/codepage-1.15.0.tgz";
        sha512 = "3g6NUTPd/YtuuGrhMnOMRjFc+LJw/bnMp3+0r/Wcz3IXUuCosKRJvMphm5+Q+bvTVGcJJuRvVLuYba+WojaFaA==";
      };
    };
    "coffee-script-1.12.7" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.12.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.12.7.tgz";
        sha512 = "fLeEhqwymYat/MpTPUjSKHVYYl0ec2mOyALEMLmzr5i1isuG+6jfI2j2d5oBO3VIzgUXgBVIcOT9uH1TFxBckw==";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha512 = "OsSVtHK8Ir8r3+Fxw/b4jS1ZLPXkV6ZxDRJQzeD7qo0SqMXWrHDM71DgYzPMHY8SFJ0Ao+nNU2p1MmwdzKqPrw==";
      };
    };
    "commander-12.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-12.1.0.tgz";
        sha512 = "Vw8qHK3bZM9y/P10u3Vib8o/DdkvA2OtPtZvD871QKjy74Wj1WSKFILMPRPSdUSx5RFK1arlJzEtA4PkFgnbuA==";
      };
    };
    "commander-2.13.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.13.0.tgz";
        sha512 = "MVuS359B+YzaWqjCL/c+22gfryv+mCBPHAv3zyVI2GN8EY6IRP8VwtasXn8jyyhvvq84R4ImN1OKRtcbIasjYA==";
      };
    };
    "commander-2.14.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.14.1.tgz";
        sha512 = "+YR16o3rK53SmWHU3rEM3tPAh2rwb1yPcQX5irVn7mb0gXbwuCCrnkbV5+PBfETdfg1vui07nM6PCG1zndcjQw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "crc-32-1.2.2" = {
      name = "crc-32";
      packageName = "crc-32";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc-32/-/crc-32-1.2.2.tgz";
        sha512 = "ROmzCKrTnOwybPcJApAA6WBWij23HVfGVNKqqrZpuyZOHqK2CwHSvpGuyt/UNNvaIjEd8X5IFGp4Mh+Ie1IHJQ==";
      };
    };
    "cson-4.1.0" = {
      name = "cson";
      packageName = "cson";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cson/-/cson-4.1.0.tgz";
        sha512 = "WJE4sajPn19i2NVs7PUjODPoEcwE7NEmVDsXYxyYca7UOcWcGIZM7xPtI0VQeOWxNbCLI+uvuP0BetJJfsspxQ==";
      };
    };
    "cson-parser-1.3.5" = {
      name = "cson-parser";
      packageName = "cson-parser";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cson-parser/-/cson-parser-1.3.5.tgz";
        sha512 = "Pchz4dDkyafUL4V3xBuP9Os8Hu9VU96R+MxuTKh7NR+D866UiWrhBiSLbfuvwApEaJzpXhXTr3iPe4lFtXLzcQ==";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha512 = "jRFi8UDGo6j+odZiEpjazZaWqEal3w/basFjQHQEwVtZJGDpxbH1MeYluwCS8Xq5wmLJooDlMgvVarmWfGM44g==";
      };
    };
    "data-view-buffer-1.0.1" = {
      name = "data-view-buffer";
      packageName = "data-view-buffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-view-buffer/-/data-view-buffer-1.0.1.tgz";
        sha512 = "0lht7OugA5x3iJLOWFhWK/5ehONdprk0ISXqVFn/NFrDu+cuc8iADFrGQz5BnRK7LLU3JmkbXSxaqX+/mXYtUA==";
      };
    };
    "data-view-byte-length-1.0.1" = {
      name = "data-view-byte-length";
      packageName = "data-view-byte-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-view-byte-length/-/data-view-byte-length-1.0.1.tgz";
        sha512 = "4J7wRJD3ABAzr8wP+OcIcqq2dlUKp4DVflx++hs5h5ZKydWMI6/D/fAot+yh6g2tHh8fLFTvNOaVN357NvSrOQ==";
      };
    };
    "data-view-byte-offset-1.0.0" = {
      name = "data-view-byte-offset";
      packageName = "data-view-byte-offset";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-view-byte-offset/-/data-view-byte-offset-1.0.0.tgz";
        sha512 = "t/Ygsytq+R995EJ5PZlD4Cu56sWa8InXySaViRzw9apusqsOO2bQP+SbYzAhR0pFKoB+43lYy8rWban9JSuXnA==";
      };
    };
    "date-extended-0.0.6" = {
      name = "date-extended";
      packageName = "date-extended";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-extended/-/date-extended-0.0.6.tgz";
        sha512 = "v9a2QLTVn1GQGXf02TQaSvNfeXA/V1FL2Tr0OQYqjI5+L9T5jEtCpLYG01sxFk+m1OtwMxydkKa8NKcflANAoQ==";
      };
    };
    "deasync-0.1.29" = {
      name = "deasync";
      packageName = "deasync";
      version = "0.1.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/deasync/-/deasync-0.1.29.tgz";
        sha512 = "EBtfUhVX23CE9GR6m+F8WPeImEE4hR/FW9RkK0PMl9V1t283s0elqsTD8EZjaKX28SY1BW2rYfCgNsAYdpamUw==";
      };
    };
    "deasync-promise-1.0.1" = {
      name = "deasync-promise";
      packageName = "deasync-promise";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deasync-promise/-/deasync-promise-1.0.1.tgz";
        sha512 = "VzJ6J6beJcSXM7SMVhug3JNZzLiPGUNJWDuevXcFeXQCa+zlnP7ZrByI+8DZQZ3AoZJj9W32ceqF6JBKmsTdgg==";
      };
    };
    "declare.js-0.0.8" = {
      name = "declare.js";
      packageName = "declare.js";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/declare.js/-/declare.js-0.0.8.tgz";
        sha512 = "O659hy1gcHef7JnwtqdQlrj2c5DAEgtxm8pgFXofW7eUE1L4FjsSLlziovWcrOJAOFlEPaOJshY+0hBWCG/AnA==";
      };
    };
    "define-data-property-1.1.4" = {
      name = "define-data-property";
      packageName = "define-data-property";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-data-property/-/define-data-property-1.1.4.tgz";
        sha512 = "rBMvIzlpA8v6E+SJZoo++HAYqsLrkg7MSfIinMPFhmkorw7X+dOXVJQs+QT69zGkzMyfDnIMN2Wid1+NbL3T+A==";
      };
    };
    "define-properties-1.2.1" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.2.1.tgz";
        sha512 = "8QmQKqEASLd5nx0U1B1okLElbUuuttJ/AnYmRXbbbGDWh6uS208EjD4Xqq/I9wK7u0v6O08XhTWnt5XtEbR6Dg==";
      };
    };
    "eachr-3.3.0" = {
      name = "eachr";
      packageName = "eachr";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eachr/-/eachr-3.3.0.tgz";
        sha512 = "yKWuGwOE283CTgbEuvqXXusLH4VBXnY2nZbDkeWev+cpAXY6zCIADSPLdvfkAROc0t8S4l07U1fateCdEDuuvg==";
      };
    };
    "editions-2.3.1" = {
      name = "editions";
      packageName = "editions";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/editions/-/editions-2.3.1.tgz";
        sha512 = "ptGvkwTvGdGfC0hfhKg0MT+TRLRKGtUiWGBInxOm5pz7ssADezahjCUaYuZ8Dr+C05FW0AECIIPt4WBxVINEhA==";
      };
    };
    "errlop-2.2.0" = {
      name = "errlop";
      packageName = "errlop";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/errlop/-/errlop-2.2.0.tgz";
        sha512 = "e64Qj9+4aZzjzzFpZC7p5kmm/ccCrbLhAJplhsDXQFs87XTsXwOpH4s1Io2s90Tau/8r2j9f4l/thhDevRjzxw==";
      };
    };
    "es-abstract-1.23.3" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.23.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.23.3.tgz";
        sha512 = "e+HfNH61Bj1X9/jLc5v1owaLYuHdeHHSQlkhCBiTK8rBvKaULl/beGMxwrMXjpYrv4pz22BlY570vVePA2ho4A==";
      };
    };
    "es-array-method-boxes-properly-1.0.0" = {
      name = "es-array-method-boxes-properly";
      packageName = "es-array-method-boxes-properly";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-array-method-boxes-properly/-/es-array-method-boxes-properly-1.0.0.tgz";
        sha512 = "wd6JXUmyHmt8T5a2xreUwKcGPq6f1f+WwIJkijUqiGcJz1qqnZgP6XIK+QyIWU5lT7imeNxUll48bziG+TSYcA==";
      };
    };
    "es-define-property-1.0.0" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.0.tgz";
        sha512 = "jxayLKShrEqqzJ0eumQbVhTYQM27CfT1T35+gCgDFoL82JLsXqTJ76zv6A0YLOgEnLUMvLzsDsGIrl8NFpT2gQ==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.0.0" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.0.0.tgz";
        sha512 = "MZ4iQ6JwHOBQjahnjwaC1ZtIBH+2ohjamzAO3oaHcXYup7qxjF2fixyH+Q71voWHeOkI2q/TnJao/KfXYIZWbw==";
      };
    };
    "es-set-tostringtag-2.0.3" = {
      name = "es-set-tostringtag";
      packageName = "es-set-tostringtag";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-set-tostringtag/-/es-set-tostringtag-2.0.3.tgz";
        sha512 = "3T8uNMC3OQTHkFUsFq8r/BwAXLHvU/9O9mE0fBc/MY5iq/8H7ncvO947LmYA6ldWw9Uh8Yhf25zu6n7nML5QWQ==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "exit-on-epipe-1.0.1" = {
      name = "exit-on-epipe";
      packageName = "exit-on-epipe";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit-on-epipe/-/exit-on-epipe-1.0.1.tgz";
        sha512 = "h2z5mrROTxce56S+pnvAV890uu7ls7f1kEvVGJbw1OlFH3/mlJ5bkXu0KRyW94v37zzHPiUd55iLn3DA7TjWpw==";
      };
    };
    "extended-0.0.6" = {
      name = "extended";
      packageName = "extended";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/extended/-/extended-0.0.6.tgz";
        sha512 = "rvAV3BDGsV1SYGzUOu7aO0k82quhfl0QAyZudYhAcTeIr1rPbBnyOhOlkCLwLpDfP7HyKAWAPNSjRb9p7lE3rg==";
      };
    };
    "extender-0.0.10" = {
      name = "extender";
      packageName = "extender";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/extender/-/extender-0.0.10.tgz";
        sha512 = "iPLUHZJaNW6RuOShQX33ZpewEUIlijFBcsXnKWyiYERKWPsFxfKgx8J0xRz29hKQWPFFPACgBW6cHM7Ke1pfaA==";
      };
    };
    "extract-opts-3.4.0" = {
      name = "extract-opts";
      packageName = "extract-opts";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extract-opts/-/extract-opts-3.4.0.tgz";
        sha512 = "M7Y+1cJDkzOWqvGH5F/V2qgkD6+uitW3NV9rQGl+pLSVuXZ4IDDQgxxMeLPKcWUyfypBWczIILiroSuhXG7Ytg==";
      };
    };
    "fast-csv-2.5.0" = {
      name = "fast-csv";
      packageName = "fast-csv";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-csv/-/fast-csv-2.5.0.tgz";
        sha512 = "M/9ezLU9/uDwvDZTt9sNFJa0iLDUsbhYJwPtnE0D9MjeuB6DY9wRCyUPZta9iI6cSz5wBWGaUPL61QH8h92cNA==";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha512 = "fueX787WZKCV0Is4/T2cyAdM4+x1S3MXXOAhavE1ys/W42SHAPacLTQhucja22QBYrfGw50M2sRiXPtTGv9Ymw==";
      };
    };
    "fast-json-patch-0.5.7" = {
      name = "fast-json-patch";
      packageName = "fast-json-patch";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-patch/-/fast-json-patch-0.5.7.tgz";
        sha512 = "NhO4vmGg6SNtDenXBGMmtZ9el0BCNsEr009bI+qpMaqt7q690SDXiHnyGVUESsx7wLtSA4+lrHp8f+OekAlHtw==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "jqYfLp7mo9vIyQf8ykW2v7A+2N4QjeCeI5+Dz9XraiO1ign81wjiH7Fb9vSOWvQfNtmSa4H2RoQTrrXivdUZmw==";
      };
    };
    "format-unicorn-1.1.1" = {
      name = "format-unicorn";
      packageName = "format-unicorn";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/format-unicorn/-/format-unicorn-1.1.1.tgz";
        sha512 = "MEjmrLmOsxswQC+TLVgGRZTRw+QSwMTQ0aqnkWPMAw1jKcO710mET0GMwoxrm0GxN0nSSBSUVaxC4MNYyrDXHQ==";
      };
    };
    "frac-0.3.1" = {
      name = "frac";
      packageName = "frac";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/frac/-/frac-0.3.1.tgz";
        sha512 = "1Lzf2jOjhIkRaa013KlxNOn2D9FemmQNeYUDpEIyPeFXmpLvbZXJOlaayMBT6JKXx+afQFgQ1QJ4kaF7Z07QFQ==";
      };
    };
    "frac-1.1.2" = {
      name = "frac";
      packageName = "frac";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/frac/-/frac-1.1.2.tgz";
        sha512 = "w/XBfkibaTl3YDqASwfDUqkna4Z2p9cFSr1aHDt0WoMTECnRfBOv2WArlZILlqgWlmdIlALXGpM2AOhEk5W3IA==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "function.prototype.name-1.1.6" = {
      name = "function.prototype.name";
      packageName = "function.prototype.name";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/function.prototype.name/-/function.prototype.name-1.1.6.tgz";
        sha512 = "Z5kx79swU5P27WEayXM1tBi5Ze/lbIyiNgU3qyXUOf9b2rgXYyF9Dy9Cx+IQv/Lc8WCG6L82zwUPpSS9hGehIg==";
      };
    };
    "functions-have-names-1.2.3" = {
      name = "functions-have-names";
      packageName = "functions-have-names";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/functions-have-names/-/functions-have-names-1.2.3.tgz";
        sha512 = "xckBUXyTIqT97tq2x2AMb+g163b5JFysYk0x4qxNFwbfQkmNZoiRHb6sPzI9/QV33WeuvVYBUIiD4NzNIyqaRQ==";
      };
    };
    "get-intrinsic-1.2.4" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.4.tgz";
        sha512 = "5uYhsJH8VJBTv7oslg4BznJYhDoRI6waYCxMmCdnTrcCrHA/fCFKoTFz2JKKE0HdDFUF7/oQuhzumXJK7paBRQ==";
      };
    };
    "get-symbol-description-1.0.2" = {
      name = "get-symbol-description";
      packageName = "get-symbol-description";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-symbol-description/-/get-symbol-description-1.0.2.tgz";
        sha512 = "g0QYk1dZBxGwk+Ngc+ltRH2IBp2f7zBkBMBJZCDerh6EhlhSR6+9irMCuT/09zD6qkarHUSn529sK/yL4S27mg==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "globalthis-1.0.4" = {
      name = "globalthis";
      packageName = "globalthis";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/globalthis/-/globalthis-1.0.4.tgz";
        sha512 = "DpLKbNU4WylpxJykQujfCcwYWiV/Jhm50Goo0wrVILAv5jOr9d+H+UR3PhSCD2rCCEIg0uc+G+muBTwD54JhDQ==";
      };
    };
    "gopd-1.0.1" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.0.1.tgz";
        sha512 = "d65bNlIadxvpb/A2abVdlqKqV563juRnZ1Wtk6s1sIR8uNsXR70xqIzVqxVf1eTqDunwT2MkczEeaezCKTZhwA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-bigints-1.0.2" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.2.tgz";
        sha512 = "tSvCKtBr9lkF0Ex0aQiP9N+OpV4zi2r/Nee5VkRDbaqv35RLYMzbwQfFSZZH0kR+Rd6302UJZ2p/bJCEoR3VoQ==";
      };
    };
    "has-property-descriptors-1.0.2" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.2.tgz";
        sha512 = "55JNKuIW+vq4Ke1BjOTjM2YctQIvCT7GFzHwmfZPGo5wnrgkid0YQtnAleFSqumZm4az3n2BS+erby5ipJdgrg==";
      };
    };
    "has-proto-1.0.3" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.3.tgz";
        sha512 = "SJ1amZAJUiZS+PhsVLf5tGydlaVB8EdFpaSO4gmiUKUOxk8qzn5AIy4ZeJUmh22znIdk/uMAUT2pl3FxzVUH+Q==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "hjson-2.4.3" = {
      name = "hjson";
      packageName = "hjson";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hjson/-/hjson-2.4.3.tgz";
        sha512 = "gpLABogUGlxNdW/PwdEYRBMsfU3Jvl96qkXx2D+GZIg0xllpNkuscV53Ibb1Wk4goyY6Hfm63yMRaNUExFe0hw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "internal-slot-1.0.7" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.7.tgz";
        sha512 = "NGnrKwXzSms2qUUih/ILZ5JBqNTSa1+ZmP6flaIp6KmSElgE9qdndzS3cqjrDovwFdmwsGsLdeFgB6suw+1e9g==";
      };
    };
    "is-array-buffer-3.0.4" = {
      name = "is-array-buffer";
      packageName = "is-array-buffer";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-array-buffer/-/is-array-buffer-3.0.4.tgz";
        sha512 = "wcjaerHw0ydZwfhiKbXJWLDY8A7yV7KhjQOpb83hGgGfId/aQa4TOvwyzn2PuswW2gPCYEL/nEAiSVpdOj1lXw==";
      };
    };
    "is-bigint-1.0.4" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.4.tgz";
        sha512 = "zB9CruMamjym81i2JZ3UMn54PKGsQzsJeo6xvN3HJJ4CAsQNB6iRutp2To77OfCNuoxspsIhzaPoO1zyCEhFOg==";
      };
    };
    "is-boolean-object-1.1.2" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz";
        sha512 = "gDYaKHJmnj4aWxyj6YHyXVpdQawtVLHU5cb+eztPGczf6cjuTdwve5ZIEfgXqH4e57An1D1AKf8CZ3kYrQRqYA==";
      };
    };
    "is-callable-1.2.7" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.7.tgz";
        sha512 = "1BC0BVFhS/p0qtw6enp8e+8OD0UrK0oFLztSjNzhcKA3WDuJxxAPXzPuPtKkjEY9UUoEWlX/8fgKeu2S8i9JTA==";
      };
    };
    "is-data-view-1.0.1" = {
      name = "is-data-view";
      packageName = "is-data-view";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-view/-/is-data-view-1.0.1.tgz";
        sha512 = "AHkaJrsUVW6wq6JS8y3JnM/GJF/9cf+k20+iDzlSaJrinEo5+7vRiteOSwBhHRiAyQATN1AmY4hwzxJKPmYf+w==";
      };
    };
    "is-date-object-1.0.5" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.5.tgz";
        sha512 = "9YQaSxsAiSwcvS33MBk3wTCVnWK+HhF8VZR2jRxehM16QcVOdHqPn4VPHmRK4lSr38n9JriurInLcP90xsYNfQ==";
      };
    };
    "is-extended-0.0.10" = {
      name = "is-extended";
      packageName = "is-extended";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extended/-/is-extended-0.0.10.tgz";
        sha512 = "qp+HR+L9QXbgFurvqiVgD+JiGyUboRgICNzCXmbiLtZBFVSNFbxRsI4q7Be9mCWTO5PoO1IxoWp5sl+j5b83FA==";
      };
    };
    "is-negative-zero-2.0.3" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.3.tgz";
        sha512 = "5KoIu2Ngpyek75jXodFvnafB6DJgr3u8uuK0LEZJjrU19DrMD3EVERaR8sjz8CCGgpZvxPl9SuE1GMVPFHx1mw==";
      };
    };
    "is-number-object-1.0.7" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.7.tgz";
        sha512 = "k1U0IRzLMo7ZlYIfzRu23Oh6MiIFasgpb9X76eqfFZAqwH44UI4KTBvBYIZ1dSL9ZzChTB9ShHfLkR4pdW5krQ==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-shared-array-buffer-1.0.3" = {
      name = "is-shared-array-buffer";
      packageName = "is-shared-array-buffer";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-shared-array-buffer/-/is-shared-array-buffer-1.0.3.tgz";
        sha512 = "nA2hv5XIhLR3uVzDDfCIknerhx8XUKnstuOERPNNIinXG7v9u+ohXF67vxm4TPTEPU6lm61ZkwP3c9PCB97rhg==";
      };
    };
    "is-string-1.0.7" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.7.tgz";
        sha512 = "tE2UXzivje6ofPW7l23cjDOMa09gb7xlAqG6jG5ej6uPV32TlWP3NKPigtaGeHNu9fohccRYvIiZMfOOnOYUtg==";
      };
    };
    "is-symbol-1.0.4" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.4.tgz";
        sha512 = "C/CPBqKWnvdcxqIARxyOh4v1UUEOCHpgDa0WYgpKDFMszcrPcffg5uhwSgPCLD2WWxmq6isisz87tzT01tuGhg==";
      };
    };
    "is-typed-array-1.1.13" = {
      name = "is-typed-array";
      packageName = "is-typed-array";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typed-array/-/is-typed-array-1.1.13.tgz";
        sha512 = "uZ25/bUAlUY5fR4OKT4rZQEBrzQWYV9ZJYGGsUmEJ6thodVJ1HX64ePQ6Z0qPWP+m+Uq6e9UugrE38jeYsDSMw==";
      };
    };
    "is-weakref-1.0.2" = {
      name = "is-weakref";
      packageName = "is-weakref";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakref/-/is-weakref-1.0.2.tgz";
        sha512 = "qctsuLZmIQ0+vSSMfoVvyFe2+GSEvnmZ2ezTup1SBse9+twCCeial6EEi3Nc2KFcf6+qz2FBPnjXsk8xhKSaPQ==";
      };
    };
    "isarray-2.0.5" = {
      name = "isarray";
      packageName = "isarray";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-2.0.5.tgz";
        sha512 = "xHjhDr3cNBK0BzdUJSPXZntQUx/mwMS5Rw4A7lPJ90XGAO6ISP/ePDNuo0vhqOZU+UD5JoodwCAAoZQd3FeAKw==";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha512 = "4JD/Ivzg7PoW8NzdrBSr3UFwC9mHgvI7Z6z3QGBsSHgKaRTUDmyZAAKJo2UbG1kUVfS9WS8bi36N49U1xw43DA==";
      };
    };
    "json5-0.5.1" = {
      name = "json5";
      packageName = "json5";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-0.5.1.tgz";
        sha512 = "4xrs1aW+6N5DalkqSVA8fxh458CXvR99WU8WLKmq4v8eWAL86Xo3BVqyd3SkA9wEVjCMqyvvRRkshAdOnBp5rw==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "node-addon-api-1.7.2" = {
      name = "node-addon-api";
      packageName = "node-addon-api";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-1.7.2.tgz";
        sha512 = "ibPK3iA+vaY1eEjESkQkM0BbCqFOaZMiXRTtdB0u7b4djtY6JnsjvPdUHVMg6xQt3B8fpTTWHI9A+ADjM9frzg==";
      };
    };
    "object-extended-0.0.7" = {
      name = "object-extended";
      packageName = "object-extended";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-extended/-/object-extended-0.0.7.tgz";
        sha512 = "2LJYIacEXoZ1glGkAZuvA/4pfJM4Y1ShReAo9jWpBSuz89TiUCdiPqhGJJ6m97F3WjhCSRwrbgaxYEAm9dRYBw==";
      };
    };
    "object-inspect-1.13.1" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.1.tgz";
        sha512 = "5qoj1RUiKOMsCCNLV1CBiPYE10sziTsnmNxkAI/rZhiD63CF7IqdFGC/XzjWjpSgLf0LxXX3bDFIh0E18f6UhQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.5" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.5.tgz";
        sha512 = "byy+U7gp+FVwmyzKPYhW2h5l3crpmGsxl7X2s8y43IgxvG4g3QZ6CffDtsNQy1WsmZpQbO+ybo0AlW7TY6DcBQ==";
      };
    };
    "object.getownpropertydescriptors-2.1.8" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.8.tgz";
        sha512 = "qkHIGe4q0lSYMv0XI4SsBTJz3WaURhLvd0lKSgtVuOsJ2krg4SgMw3PIRQFMp07yi++UR3se2mkcLqsBNpBb/A==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "possible-typed-array-names-1.0.0" = {
      name = "possible-typed-array-names";
      packageName = "possible-typed-array-names";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/possible-typed-array-names/-/possible-typed-array-names-1.0.0.tgz";
        sha512 = "d7Uw+eZoloe0EHDIYoe+bQ5WXnGMOpmiZFTuMWCwpjzzkL2nTjcKiAk4hh8TjnGye2TwWOk3UXucZ+3rbmBa8Q==";
      };
    };
    "printj-1.1.2" = {
      name = "printj";
      packageName = "printj";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/printj/-/printj-1.1.2.tgz";
        sha512 = "zA2SmoLaxZyArQTOPj5LXecR+RagfPSU5Kw1qP+jkWeNlrq+eJZyY2oS68SU1Z/7/myXM4lo9716laOFAVStCQ==";
      };
    };
    "regexp.prototype.flags-1.5.2" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.5.2.tgz";
        sha512 = "NcDiDkTLuPR+++OCKB0nWafEmhg/Da8aUPLPMQbK+bxKKCm1/S5he+AqYa4PlMCVBalb4/yxIRub6qkEx5yJbw==";
      };
    };
    "requirefresh-2.3.0" = {
      name = "requirefresh";
      packageName = "requirefresh";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/requirefresh/-/requirefresh-2.3.0.tgz";
        sha512 = "oskKAg0pSlPnJAkFMrcqrHeCGzYunl4Hkl+N/NW3nnFWDHRg97yb475HtF5ax8LP9i8QvVkenVIhjNb+h+P7nA==";
      };
    };
    "safe-array-concat-1.1.2" = {
      name = "safe-array-concat";
      packageName = "safe-array-concat";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-array-concat/-/safe-array-concat-1.1.2.tgz";
        sha512 = "vj6RsCsWBCf19jIeHEfkRMw8DPiBb+DMXklQ/1SGDHOMlHdPUkZXFQ2YdplS23zESTijAcurb1aSgJA3AgMu1Q==";
      };
    };
    "safe-regex-test-1.0.3" = {
      name = "safe-regex-test";
      packageName = "safe-regex-test";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex-test/-/safe-regex-test-1.0.3.tgz";
        sha512 = "CdASjNJPvRa7roO6Ra/gLYBTzYzzPyyBXxIMdGW3USQLyjWEls2RgW5UBTXaQVp+OrpeCK3bLem8smtmheoRuw==";
      };
    };
    "safefs-4.2.0" = {
      name = "safefs";
      packageName = "safefs";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safefs/-/safefs-4.2.0.tgz";
        sha512 = "1amPBO92jw/hWS+gH/u7z7EL7YxaJ8WecBQl49tMQ6Y6EQfndxNNKwlPqDOcwpUetdmK6nKLoVdjybVScRwq5A==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.3.0" = {
      name = "sax";
      packageName = "sax";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.3.0.tgz";
        sha512 = "0s+oAmw9zLl1V1cS9BtZN7JAd0cW5e0QH4W3LWEK6a4LaLEA2OTpGYWDY+6XasBLtz6wkm3u1xRw95mRuJ59WA==";
      };
    };
    "semver-6.3.1" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.1.tgz";
        sha512 = "BR7VvDCVHO+q2xBEWskxS6DJE1qRnb7DxzUrogb71CWoSficBxYsiAGd+Kl0mmq/MprG9yArRkyrQxTO6XjMzA==";
      };
    };
    "set-function-length-1.2.2" = {
      name = "set-function-length";
      packageName = "set-function-length";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-function-length/-/set-function-length-1.2.2.tgz";
        sha512 = "pgRc4hJ4/sNjWCSS9AmnS40x3bNMDTknHgL5UaMBTMyJnU90EgWh1Rz+MC9eFu4BuN/UwZjKQuY/1v3rM7HMfg==";
      };
    };
    "set-function-name-2.0.2" = {
      name = "set-function-name";
      packageName = "set-function-name";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-function-name/-/set-function-name-2.0.2.tgz";
        sha512 = "7PGFlmtwsEADb0WYyvCMa1t+yke6daIG4Wirafur5kcf+MhUnPms1UeR0CKQdTZD81yESwMHbtn+TR+dMviakQ==";
      };
    };
    "side-channel-1.0.6" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.6.tgz";
        sha512 = "fDW/EZ6Q9RiO8eFG8Hj+7u/oW+XrPTIChwCOM2+th2A6OblDtYYIpve9m+KvI9Z4C9qSEXlaGR6bTEYHReuglA==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha512 = "D9cPgkvLlV3t3IzL0D0YLvGA9Ahk4PcvVwUbN0dSGr1aP0Nrt4AEnTUbuGvquEC0mA64Gqt1fzirlRs5ibXx8g==";
      };
    };
    "ssf-0.10.3" = {
      name = "ssf";
      packageName = "ssf";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssf/-/ssf-0.10.3.tgz";
        sha512 = "pRuUdW0WwyB2doSqqjWyzwCD6PkfxpHAHdZp39K3dp/Hq7f+xfMwNAWIi16DyrRg4gg9c/RvLYkJTSawTPTm1w==";
      };
    };
    "ssf-0.8.2" = {
      name = "ssf";
      packageName = "ssf";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssf/-/ssf-0.8.2.tgz";
        sha512 = "+ZkFDAG+ImJ48DcZvabx6YTrZ67DKkM0kbyOOtH73mbUEvNhQWWgRZrHC8+k7GuGKWQnACYLi7bj0eCt1jmosQ==";
      };
    };
    "string-extended-0.0.8" = {
      name = "string-extended";
      packageName = "string-extended";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-extended/-/string-extended-0.0.8.tgz";
        sha512 = "CK46p3AxBvBhJbBi6WrF9bCcaWH20E4NwlLSzpooG2nXWvcP2gy2YR8VN6fSwZyrbcvL4S4zoNKbR0QG52X4rw==";
      };
    };
    "string.prototype.trim-1.2.9" = {
      name = "string.prototype.trim";
      packageName = "string.prototype.trim";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trim/-/string.prototype.trim-1.2.9.tgz";
        sha512 = "klHuCNxiMZ8MlsOihJhJEBJAiMVqU3Z2nEXWfWnIqjN0gEFS9J9+IxKozWWtQGcgoa1WUZzLjKPTr4ZHNFTFxw==";
      };
    };
    "string.prototype.trimend-1.0.8" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.8.tgz";
        sha512 = "p73uL5VCHCO2BZZ6krwwQE3kCzM7NKmis8S//xEC6fQonchbum4eP6kR4DLEjQFO3Wnj3Fuo8NM0kOSjVdHjZQ==";
      };
    };
    "string.prototype.trimstart-1.0.8" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.8.tgz";
        sha512 = "UXSH262CSZY1tfu3G3Secr6uGLCFVPMhIqHjlgCUtCCcgihYc/xKs9djMTMUOb2j1mVSeU8EU6NWc/iQKU6Gfg==";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha512 = "4gB8na07fecVVkOI6Rs4e7T6NOTki5EmL7TUduTs6bu3EdnSycntVJ4re8kgZA+wx9IueI2Y11bfbgwtzuE0KQ==";
      };
    };
    "toml-j0.4-1.1.1" = {
      name = "toml-j0.4";
      packageName = "toml-j0.4";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toml-j0.4/-/toml-j0.4-1.1.1.tgz";
        sha512 = "lYK5otg0+cto8YmsWcPEfeiTiC/VU6P6HA6ooaYI9K/KYT24Jg0BrYtRZK1K3cwakSMyh6nttfJL9RmQH0gyCg==";
      };
    };
    "tomlify-j0.4-2.2.1" = {
      name = "tomlify-j0.4";
      packageName = "tomlify-j0.4";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tomlify-j0.4/-/tomlify-j0.4-2.2.1.tgz";
        sha512 = "0kCocYX8ujnbK6jQ9e+g9GLiCIfVkFaCB3DCTQDP7J79gPVZVmZgQZ/KUNe1a6hUfrmHHaErVGUjedfpaX5EZw==";
      };
    };
    "typechecker-4.11.0" = {
      name = "typechecker";
      packageName = "typechecker";
      version = "4.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typechecker/-/typechecker-4.11.0.tgz";
        sha512 = "lz39Mc/d1UBcF/uQFL5P8L+oWdIn/stvkUgHf0tPRW4aEwGGErewNXo2Nb6We2WslWifn00rhcHbbRWRcTGhuw==";
      };
    };
    "typed-array-buffer-1.0.2" = {
      name = "typed-array-buffer";
      packageName = "typed-array-buffer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-buffer/-/typed-array-buffer-1.0.2.tgz";
        sha512 = "gEymJYKZtKXzzBzM4jqa9w6Q1Jjm7x2d+sh19AdsD4wqnMPDYyvwpsIc2Q/835kHuo3BEQ7CjelGhfTsoBb2MQ==";
      };
    };
    "typed-array-byte-length-1.0.1" = {
      name = "typed-array-byte-length";
      packageName = "typed-array-byte-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-byte-length/-/typed-array-byte-length-1.0.1.tgz";
        sha512 = "3iMJ9q0ao7WE9tWcaYKIptkNBuOIcZCCT0d4MRvuuH88fEoEH62IuQe0OtraD3ebQEoTRk8XCBoknUNc1Y67pw==";
      };
    };
    "typed-array-byte-offset-1.0.2" = {
      name = "typed-array-byte-offset";
      packageName = "typed-array-byte-offset";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-byte-offset/-/typed-array-byte-offset-1.0.2.tgz";
        sha512 = "Ous0vodHa56FviZucS2E63zkgtgrACj7omjwd/8lTEMEPFFyjfixMZ1ZXenpgCFBBt4EC1J2XsyVS2gkG0eTFA==";
      };
    };
    "typed-array-length-1.0.6" = {
      name = "typed-array-length";
      packageName = "typed-array-length";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-length/-/typed-array-length-1.0.6.tgz";
        sha512 = "/OxDN6OtAk5KBpGb28T+HZc2M+ADtvRxXrKKbUwtsLgdoxgX13hyy7ek6bFRl5+aBs2yZzB0c4CnQfAtVypW/g==";
      };
    };
    "typescript-2.9.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "2.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-2.9.2.tgz";
        sha512 = "Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w==";
      };
    };
    "unbox-primitive-1.0.2" = {
      name = "unbox-primitive";
      packageName = "unbox-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbox-primitive/-/unbox-primitive-1.0.2.tgz";
        sha512 = "61pPlCD9h51VoreyJ0BReideM3MDKMKnh6+V9L08331ipq6Q8OFXZYiqP6n/tbHx4s5I9uRhcye6BrbkizkBDw==";
      };
    };
    "util.promisify-1.1.2" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.1.2.tgz";
        sha512 = "PBdZ03m1kBnQ5cjjO0ZvJMJS+QsbyIcFwi4hY4U76OQsCO9JrOYjbCFgIF76ccFg9xnJo7ZHPkqyj1GqmdS7MA==";
      };
    };
    "voc-1.2.0" = {
      name = "voc";
      packageName = "voc";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/voc/-/voc-1.2.0.tgz";
        sha512 = "BOuDjFFYvJdZO6e/N65AlaDItXo2TgyLjeyRYcqgAPkXpp5yTJcvkL2n+syO1r9Qc5g96tfBD2tuiMhYDmaGcA==";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "which-typed-array-1.1.15" = {
      name = "which-typed-array";
      packageName = "which-typed-array";
      version = "1.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-typed-array/-/which-typed-array-1.1.15.tgz";
        sha512 = "oV0jmFtUky6CXfkqehVvBP/LSWJ2sy4vWMioiENyJLePrBO/yKyV9OyJySfAKosh+RYkIl5zJCNZ8/4JncrpdA==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "xlsjs-0.7.6" = {
      name = "xlsjs";
      packageName = "xlsjs";
      version = "0.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/xlsjs/-/xlsjs-0.7.6.tgz";
        sha512 = "IQtL2z+BVYaIVzEhknZ1YBr8ItUbqiS7kaQZ3O35/k1q+kSgjVxmzwno6r3EbBgEWhrVCad2mKbnFeMmEE5zdw==";
      };
    };
    "xlsx-0.11.19" = {
      name = "xlsx";
      packageName = "xlsx";
      version = "0.11.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/xlsx/-/xlsx-0.11.19.tgz";
        sha512 = "UTfD64o5Ka/E6QHL12fzcq5wnt9MCtuwgoUdYSTDxjjDkhNmZwSfPlJH/+Yh8vE6nU/0ax3MXNrc9AP4haAmIg==";
      };
    };
    "xml2js-0.4.17" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.17.tgz";
        sha512 = "1O7wk/NTQN0UEOItIYTxK4qP4sMUVU60MbF4Nj0a8jd6eebMXOicVI/KFOEsYKKH4uBpx6XG9ZGZctXK5rtO5Q==";
      };
    };
    "xmlbuilder-4.2.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-4.2.1.tgz";
        sha512 = "oEePiEefhQhAeUnwRnIBLBWmk/fsWWbQ53EEWsRuzECbQ3m5o/Esmq6H47CYYwSLW+Ynt0rS9hd0pd2ogMAWjg==";
      };
    };
  };
in
{
  pajv = nodeEnv.buildNodePackage {
    name = "pajv";
    packageName = "pajv";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pajv/-/pajv-1.2.0.tgz";
      sha512 = "bNJ4USHijOH4ZX64HlzIdooa0KS+o+nOqVQZtHXzzH4OB+hYNXTyPQ07Rq8gWaTJvt1Hu89aeWlmKARgcdo2IQ==";
    };
    dependencies = [
      sources."adler-32-1.2.0"
      sources."ajv-5.5.2"
      sources."any-json-3.1.0"
      sources."argparse-1.0.10"
      sources."arguments-extended-0.0.3"
      sources."array-buffer-byte-length-1.0.1"
      sources."array-extended-0.0.11"
      sources."array.prototype.reduce-1.0.7"
      sources."arraybuffer.prototype.slice-1.0.3"
      sources."assert-plus-1.0.0"
      sources."available-typed-arrays-1.0.7"
      sources."balanced-match-1.0.2"
      sources."bindings-1.5.0"
      sources."brace-expansion-1.1.11"
      sources."call-bind-1.0.7"
      sources."cfb-0.11.1"
      sources."co-4.6.0"
      sources."codepage-1.15.0"
      sources."coffee-script-1.12.7"
      sources."colors-0.6.2"
      sources."commander-12.1.0"
      sources."concat-map-0.0.1"
      sources."crc-32-1.2.2"
      sources."cson-4.1.0"
      sources."cson-parser-1.3.5"
      sources."dashdash-1.14.1"
      sources."data-view-buffer-1.0.1"
      sources."data-view-byte-length-1.0.1"
      sources."data-view-byte-offset-1.0.0"
      sources."date-extended-0.0.6"
      sources."deasync-0.1.29"
      sources."deasync-promise-1.0.1"
      sources."declare.js-0.0.8"
      sources."define-data-property-1.1.4"
      sources."define-properties-1.2.1"
      sources."eachr-3.3.0"
      sources."editions-2.3.1"
      sources."errlop-2.2.0"
      sources."es-abstract-1.23.3"
      sources."es-array-method-boxes-properly-1.0.0"
      sources."es-define-property-1.0.0"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.0.0"
      sources."es-set-tostringtag-2.0.3"
      sources."es-to-primitive-1.2.1"
      sources."esprima-4.0.1"
      sources."exit-on-epipe-1.0.1"
      sources."extended-0.0.6"
      sources."extender-0.0.10"
      sources."extract-opts-3.4.0"
      sources."fast-csv-2.5.0"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-patch-0.5.7"
      sources."fast-json-stable-stringify-2.1.0"
      sources."file-uri-to-path-1.0.0"
      sources."for-each-0.3.3"
      sources."format-unicorn-1.1.1"
      sources."frac-0.3.1"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.2"
      sources."function.prototype.name-1.1.6"
      sources."functions-have-names-1.2.3"
      sources."get-intrinsic-1.2.4"
      sources."get-symbol-description-1.0.2"
      sources."glob-7.2.3"
      sources."globalthis-1.0.4"
      sources."gopd-1.0.1"
      sources."graceful-fs-4.2.11"
      sources."has-bigints-1.0.2"
      sources."has-property-descriptors-1.0.2"
      sources."has-proto-1.0.3"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."hjson-2.4.3"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."internal-slot-1.0.7"
      sources."is-array-buffer-3.0.4"
      sources."is-bigint-1.0.4"
      sources."is-boolean-object-1.1.2"
      sources."is-callable-1.2.7"
      sources."is-data-view-1.0.1"
      sources."is-date-object-1.0.5"
      sources."is-extended-0.0.10"
      sources."is-negative-zero-2.0.3"
      sources."is-number-object-1.0.7"
      sources."is-regex-1.1.4"
      sources."is-shared-array-buffer-1.0.3"
      sources."is-string-1.0.7"
      sources."is-symbol-1.0.4"
      sources."is-typed-array-1.1.13"
      sources."is-weakref-1.0.2"
      sources."isarray-2.0.5"
      sources."js-yaml-3.14.1"
      sources."json-schema-traverse-0.3.1"
      sources."json5-0.5.1"
      sources."lodash-4.17.21"
      sources."minimatch-3.1.2"
      sources."minimist-1.2.8"
      sources."node-addon-api-1.7.2"
      sources."object-extended-0.0.7"
      sources."object-inspect-1.13.1"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.5"
      sources."object.getownpropertydescriptors-2.1.8"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."possible-typed-array-names-1.0.0"
      sources."printj-1.1.2"
      sources."regexp.prototype.flags-1.5.2"
      sources."requirefresh-2.3.0"
      sources."safe-array-concat-1.1.2"
      sources."safe-regex-test-1.0.3"
      sources."safefs-4.2.0"
      sources."safer-buffer-2.1.2"
      sources."sax-1.3.0"
      sources."semver-6.3.1"
      sources."set-function-length-1.2.2"
      sources."set-function-name-2.0.2"
      sources."side-channel-1.0.6"
      sources."sprintf-js-1.0.3"
      sources."ssf-0.8.2"
      sources."string-extended-0.0.8"
      sources."string.prototype.trim-1.2.9"
      sources."string.prototype.trimend-1.0.8"
      sources."string.prototype.trimstart-1.0.8"
      sources."strip-json-comments-2.0.1"
      sources."toml-j0.4-1.1.1"
      sources."tomlify-j0.4-2.2.1"
      sources."typechecker-4.11.0"
      sources."typed-array-buffer-1.0.2"
      sources."typed-array-byte-length-1.0.1"
      sources."typed-array-byte-offset-1.0.2"
      sources."typed-array-length-1.0.6"
      sources."typescript-2.9.2"
      sources."unbox-primitive-1.0.2"
      sources."util.promisify-1.1.2"
      sources."voc-1.2.0"
      sources."which-boxed-primitive-1.0.2"
      sources."which-typed-array-1.1.15"
      sources."wrappy-1.0.2"
      sources."xlsjs-0.7.6"
      (sources."xlsx-0.11.19" // {
        dependencies = [
          (sources."cfb-1.0.8" // {
            dependencies = [
              sources."commander-2.20.3"
            ];
          })
          (sources."codepage-1.12.2" // {
            dependencies = [
              sources."commander-2.14.1"
            ];
          })
          sources."commander-2.13.0"
          sources."frac-1.1.2"
          sources."ssf-0.10.3"
        ];
      })
      sources."xml2js-0.4.17"
      sources."xmlbuilder-4.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A command line JSON Schema validator that supports many file formats. Fork of jessedc/ajv-cli.";
      homepage = "https://github.com/json-schema-everywhere/pajv#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
