apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.k8s.lillecarl.com:9998
      caBundle: placeholder
      organizationID: a5c85a84-042e-44b8-a07e-b16f00119301
      projectID: f7c5f6dc-10bc-4bd4-8ea3-b25b004e3b61
