apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ssh-icmp
spec:
  description: ""
  nodeSelector:
    matchLabels:
      node-access: ssh
  ingress:
    # "all", "world", "cluster", "host", "init", "ingress", "unmanaged", "remote-node", "health", "none", "kube-apiserver"
    - fromEntities:
        - cluster
        - ingress
    - toPorts:
        - ports:
            - port: "22"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "179"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
            - port: "51820"
              protocol: UDP
            - port: "60001"
              protocol: UDP
    - icmps:
        - fields:
            - type: EchoRequest
              family: IPv4
            - type: RouterSolicitation
              family: IPv6
            - type: RouterAdvertisement
              family: IPv6
            - type: NeighborSolicitation
              family: IPv6
            - type: NeighborAdvertisement
              family: IPv6
