#! /usr/bin/env fish

echo "Sleeping 3"
sleep 3

# Set DDC values twice because it's flaky shit
for i in 1 2;
  ddcutil -d 1 setvcp 0x60 0x11
  ddcutil -d 2 setvcp 0x60 0x03
  ddcutil -d 3 setvcp 0x60 0x03
  sleep 1
end
