# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "vfio-pci"
  ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  #boot.kernelPackages = pkgs.linuxKernel.packages.linux_xanmod_latest;
  boot.initrd.kernelModules = [ "vfio-pci" ];
  boot.extraModprobeConfig = ''
    options vfio-pci ids=10de:2487,10de:228b
    blacklist nouveau
    options nouveau modeset=0
  '';
  boot.blacklistedKernelModules = [ "nouveau" "nvidia" "nvidia_drm" "nvidia_modeset" ];
  boot.kernelModules = [
    "drivetemp"
    "nct6775"
    "kvm-amd"
    "wl"
    "vfio_virqfd"
    "vfio_pci"
    "vfio_iommu_type1"
    "vfio"
  ];
  boot.kernelParams = [
    "amd_iommu=on"
    "mitigations=off"
    "iommu=pt"
    "acpi_enforce_resources=lax"
    "delayacct"
  ];

  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback.out
    usbip
    zenpower
    turbostat
    cpupower
  ];

  boot.loader = {
    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot/efi"; # ← use the same mount point here.
    };
    grub = {
      enable = true;
      device = "/dev/sda";
      efiSupport = true;
      copyKernels = true;
      mirroredBoots = [
        {
          devices = [ "/dev/sdb" ];
          path = "/boot2";
          efiSysMountPoint = "/boot2/efi";
        }
      ];
    };
  };

  boot.kernel.sysctl = {
    "vm.swappiness" = 1;
  };

  hardware.enableAllFirmware = true;
  hardware.i2c.enable = true;
  hardware.cpu.amd.updateMicrocode = true;
  powerManagement.cpuFreqGovernor = "performance";
}
